### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by roman-turchyniak** [roman-turchyniak/homepage#4]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by ForveX** [comment]
DeadPool:
The regenerating Degenerate
"Yeah. That is a gun in my pants. But that doesn't mean I'm not happy to see you..."

**Comment by roman-turchyniak** [comment]
TY
