### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by roman-turchyniak** [roman-turchyniak/homepage#5]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by ForveX** [comment]
tel: +1 DEAADPOOL 666
e-mail: deadpool@hiration.com
work(positioning): Marvel Studios

Instagramm: https://www.instagram.com/deadpool.marvel
https://www.facebook.com/OfficialTheDeadpool
