### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by roman-turchyniak** [roman-turchyniak/homepage#7]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by ForveX** [comment]
Summary:
- Mercenary, Asasin & Superhero
- Jokes a lot
- Heals faster than Wolverine

Key Skills
-Humor - 5
-Fast Healing - 5
- Swordsmanship - 4
- Martial Arts 4
-Tolerance -1

Team Leadership:
 - manager(Deadpool)
 - Assotiate(Wounder Woman)
 - Intern 1(Wolverine)
 - Intern 2(Black Panter)

References:
E.Musk : "Merc candies a way better than boring candies"
C. Norris: "He taught me all that I can do today"
